type Query {
    hello: String!
    helloName(name: String!): String!
    add(x: Int!, y: Int!): Int!

    who: String!

    users: [User]
    user(id: ID!): User

    tickets: [Ticket]
    ticket(id: ID!): Ticket

    comments: [Comment]
    comment(id: ID!): Comment
}

type Mutation {
    createTicket(title: String!, priority: Int!, text: String!): Ticket!
    deleteTicket(id: ID!): Boolean!

}

type User {
    id: ID!
    name: String!
    email: String!
    isAdmin: Boolean!
    createdAt: Date
    updatedAt: Date

    # Asszociációk
    comments: [Comment]
    tickets: [Ticket]
}

type Ticket {
    id: ID!
    title: String!
    priority: Int!
    done: Boolean!
    createdAt: Date
    updatedAt: Date

    # Asszociációk
    comments: [Comment]
    users: [User]

}

type Comment {
    id: ID!
    text: String!
    createdAt: Date
    updatedAt: Date

    # Asszociációk
    user: User
    ticket: Ticket
}
