scalar Date

type Query {
    hello(name: String): String!
    add(x: Int, y: Int): Int
    categories: [Category]
    posts: [Post]
    post(id: Int!): Post
    users: [User]
    who: String
}

input CreatePostInput {
    title: String!
    content: String!
    categoryNames: [String]
}

type CreatePostOutput {
    invalidCategories: [String]
    addedCategories: [String]
    post: Post
}

type Mutation {
    createPost(data: CreatePostInput) : CreatePostOutput
}

type Post {
    id: Int!
    title: String!
    content: String!
    createdAt: Date!
    updatedAt: Date!  
    categories: [Category]
    user: User!
}

type User {
    id: Int!
    name: String!
    email: String!
    isAdmin: Boolean!
    createdAt: Date!
    updatedAt: Date!  
}

type Category {
    id: Int!
    name: String!
    hidden: Boolean!
    createdAt: Date!
    updatedAt: Date!
    posts: [Post]
}